/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.schoolupr2;

import javax.net.ssl.SSLContext;

/**
 *
 * @author user
 */
public class MainForm extends javax.swing.JFrame {

    /** Creates new form MainForm */
    public MainForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinField1 = new com.toedter.components.JSpinField();
        Teachers = new javax.swing.JButton();
        Groups = new javax.swing.JButton();
        Subjects = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Students = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Teachers.setText("Учители");
        Teachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeachersActionPerformed(evt);
            }
        });
        getContentPane().add(Teachers, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, 250, 50));

        Groups.setText("Групи");
        Groups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GroupsActionPerformed(evt);
            }
        });
        getContentPane().add(Groups, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 510, 250, 50));

        Subjects.setText("Предмети");
        Subjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubjectsActionPerformed(evt);
            }
        });
        getContentPane().add(Subjects, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 330, 250, 50));

        Exit.setText("Изход");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 620, 250, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\SchoolUpr2_Project_System_imags\\download.jpg")); // NOI18N
        jLabel1.setText("Университет");
        jLabel1.setMaximumSize(new java.awt.Dimension(400, 221));
        jLabel1.setMinimumSize(new java.awt.Dimension(400, 221));
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 221));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 30, 960, 170));

        Students.setText("Ученици");
        Students.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentsActionPerformed(evt);
            }
        });
        getContentPane().add(Students, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 420, 250, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\SchoolUpr2_Project_System_imags\\20500622.jpg")); // NOI18N
        jLabel2.setText("\n");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -20, 1290, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void TeachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeachersActionPerformed
        // TODO add your handling code here:
        Teachers t=new Teachers();
        t.show();
        this.hide();
    }//GEN-LAST:event_TeachersActionPerformed

    private void StudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentsActionPerformed
        // TODO add your handling code here:
        Student s=new Student();
        s.show();
        this.hide();
    }//GEN-LAST:event_StudentsActionPerformed

    private void SubjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubjectsActionPerformed
        // TODO add your handling code here:
        Subjects sh=new Subjects();
        sh.show();
        this.hide();
    }//GEN-LAST:event_SubjectsActionPerformed

    private void GroupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GroupsActionPerformed
        // TODO add your handling code here:
        Groups g=new Groups();
        g.show();
        this.hide();
    }//GEN-LAST:event_GroupsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton Groups;
    private javax.swing.JButton Students;
    private javax.swing.JButton Subjects;
    private javax.swing.JButton Teachers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private com.toedter.components.JSpinField jSpinField1;
    // End of variables declaration//GEN-END:variables

}
