 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.schoolupr2;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author user
 */
public class Teachers extends javax.swing.JFrame {
String name;
String lastname;
String group;
ArrayList<Teachers> list=new ArrayList<Teachers>();

    public Teachers(String name, String lastname, String group) {
        this.name = name;
        this.lastname = lastname;
        this.group = group;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getGroup() {
        return group;
    }

    public void setGroup(String group) {
        this.group = group;
    }

    
    /**
     * Creates new form Teachers
     */
    public Teachers() {
        initComponents();
         Databasea dao = new Databasea();
           String sql1="select t.idteachers,t.name,t.last_name,g.Gname from univercitydb.teachers t INNER JOIN univercitydb.groups g on t.group=g.idgroups";
        dao.SelectTableTeachers(table1,sql1);
        dao.combo(groups);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        last_name = new javax.swing.JTextField();
        namea = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        Insert = new javax.swing.JButton();
        name1 = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        name2 = new javax.swing.JLabel();
        Update = new javax.swing.JButton();
        groups = new javax.swing.JComboBox<>();
        Gback = new javax.swing.JButton();
        name3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Учители");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 210, 60));
        getContentPane().add(last_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 166, 36));

        namea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namea.setForeground(new java.awt.Color(240, 240, 240));
        namea.setText("name");
        getContentPane().add(namea, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idteachers", "name", "last_name", "group"
            }
        ));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 220, 450, 360));

        Insert.setText("Insert");
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });
        getContentPane().add(Insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));
        getContentPane().add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 166, 37));

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, -1, -1));

        name2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name2.setForeground(new java.awt.Color(240, 240, 240));
        name2.setText("last_name");
        getContentPane().add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 79, -1));

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, -1, -1));
        getContentPane().add(groups, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 166, 34));

        Gback.setText("Back");
        Gback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GbackActionPerformed(evt);
            }
        });
        getContentPane().add(Gback, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, -1, -1));

        name3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name3.setForeground(new java.awt.Color(240, 240, 240));
        name3.setText("group");
        getContentPane().add(name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 58, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\SchoolUpr2_Project_System_imags\\book-education-board-book-cover.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertActionPerformed
        // TODO add your handling code here:
         Databasea dao=new Databasea();
          String s= name1.getText();
         String s1=last_name.getText();
         if(s.matches(".*\\d.*")==false && s1.matches(".*\\d.*")==false){
              String sql1="select t.idteachers,t.name,t.last_name,g.Gname from univercitydb.teachers t INNER JOIN univercitydb.groups g on t.group=g.idgroups";
        String name11=name1.getText();
        String lastname1=last_name.getText();
        String selected =groups.getSelectedItem().toString();
        String sql5="select idgroups from univercitydb.groups where Gname='"+selected+"'";
        dao.SelectedItem(sql5);
        String id=dao.SelectedItem(sql5);
        int id1=Integer.parseInt(id);
        String sql="INSERT INTO univercitydb.teachers" + "(name,last_name,`group`)"+ "VALUES('" + name11 + "','" + lastname1+ "','" + id1+ "')";
        dao.AddGroups(sql);
        DefaultTableModel model = (DefaultTableModel) table1.getModel();
        model.setRowCount(0);
        dao.SelectTableTeachers(table1,sql1);
        }else{
             JOptionPane.showMessageDialog(null,"Name and LastName cannot have a numbers","Warning",
        JOptionPane.WARNING_MESSAGE);
         }
    }//GEN-LAST:event_InsertActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        String sql1="select t.idteachers,t.name,t.last_name,g.Gname from univercitydb.teachers t INNER JOIN univercitydb.groups g on t.group=g.idgroups";
          int row=table1.getSelectedRow();
          String cell=table1.getModel().getValueAt(row, 0).toString();
        Databasea dao=new Databasea();
        String sql="Delete from univercitydb.teachers where idteachers="+cell;
        dao.DeleteGroups(sql);
        DefaultTableModel model = (DefaultTableModel) table1.getModel();
        model.setRowCount(0);
        dao.SelectTableTeachers(table1,sql1);
    }//GEN-LAST:event_deleteActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        Databasea dao=new Databasea();
         String s= name1.getText();
         String s1=last_name.getText();
         if(s.matches(".*\\d.*")==false && s1.matches(".*\\d.*")==false){
             String sql1="select t.idteachers,t.name,t.last_name,g.Gname from univercitydb.teachers t INNER JOIN univercitydb.groups g on t.group=g.idgroups";
        String name11=name1.getText();
        String lastname1=last_name.getText();
        String selected =groups.getSelectedItem().toString();
        String sql5="select idgroups from univercitydb.groups where Gname='"+selected+"'";
        dao.SelectedItem(sql5);
        String id=dao.SelectedItem(sql5);
        int id1=Integer.parseInt(id);
       int row=table1.getSelectedRow();
         String cell=table1.getModel().getValueAt(row, 0).toString();
         
        String sql="Update univercitydb.teachers set name='" + name11 + "',last_name='" + lastname1 +  "',`group`='" + id1 + "' where idteachers="+cell;
        dao.UpdateGroups(sql);
        DefaultTableModel model = (DefaultTableModel) table1.getModel();
        model.setRowCount(0);
        dao.SelectTableTeachers(table1,sql1);
        }else{
             JOptionPane.showMessageDialog(null,"Name and LastName cannot have a numbers","Warning",
        JOptionPane.WARNING_MESSAGE);
         }
    }//GEN-LAST:event_UpdateActionPerformed

    private void GbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GbackActionPerformed
        // TODO add your handling code here:
        MainForm open=new MainForm();
        open.show();
        this.hide();
    }//GEN-LAST:event_GbackActionPerformed

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        // TODO add your handling code here:
                        DefaultTableModel model = (DefaultTableModel) table1.getModel();
String textField1 = (String) model.getValueAt(table1.getSelectedRow(),1);
String textField2 = (String) model.getValueAt(table1.getSelectedRow(),2);
String textField3 = (String) model.getValueAt(table1.getSelectedRow(),3);
name1.setText(textField1);
last_name.setText(textField2);
groups.setSelectedItem(textField3);
    }//GEN-LAST:event_table1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teachers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Gback;
    private javax.swing.JButton Insert;
    private javax.swing.JButton Update;
    private javax.swing.JButton delete;
    private javax.swing.JComboBox<String> groups;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField last_name;
    private javax.swing.JTextField name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel namea;
    private javax.swing.JTable table1;
    // End of variables declaration//GEN-END:variables
}
