/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.carssystem;
import java.awt.Font;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.StringJoiner;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author user
 */
public class AvailableCars extends javax.swing.JFrame {
    String reg_number;
    String ram_number;
    String marka;
    int year;
    double price;
    String color;
    String haracteristics;
    String available;

    public AvailableCars(String reg_number, String ram_number, String marka, int year, double price, String color, String haracteristics, String available) {
        this.reg_number = reg_number;
        this.ram_number = ram_number;
        this.marka = marka;
        this.year = year;
        this.price = price;
        this.color = color;
        this.haracteristics = haracteristics;
        this.available = available;
    }

    public String getReg_number() {
        return reg_number;
    }

    public void setReg_number(String reg_number) {
        this.reg_number = reg_number;
    }

    public String getRam_number() {
        return ram_number;
    }

    public void setRam_number(String ram_number) {
        this.ram_number = ram_number;
    }

    public String getMarka() {
        return marka;
    }

    public void setMarka(String marka) {
        this.marka = marka;
    }

    public int getYear() {
        return year;
    }

    public void setYear(int year) {
        this.year = year;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public String getHaracteristics() {
        return haracteristics;
    }

    public void setHaracteristics(String haracteristics) {
        this.haracteristics = haracteristics;
    }

    public String getAvailable() {
        return available;
    }

    public void setAvailable(String available) {
        this.available = available;
    }

    
    ArrayList<AvailableCars> list = new ArrayList<AvailableCars>();

    public void setList(ArrayList<AvailableCars> list) {
        this.list = list;
    }

    public ArrayList<AvailableCars> getList() {
        return list;
    }
    /**
     * Creates new form Univercity
     */
    String sql1="select s.reg_number,s.numberRam,g.name,s.year,s.price,s.color,s.haracterisitcs,s.available from carssystem.availablecars s INNER JOIN carssystem.marka g on s.id_marka=g.id_marka";
    public AvailableCars() {
        initComponents();
         Databasea dao = new Databasea();
        dao.SelectTableAvailable(table1,sql1);
        dao.combo(marka1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Gback = new javax.swing.JButton();
        reg_number1 = new javax.swing.JTextField();
        fn_students = new javax.swing.JLabel();
        year1 = new javax.swing.JTextField();
        namea = new javax.swing.JLabel();
        Insert = new javax.swing.JButton();
        numberRam1 = new javax.swing.JTextField();
        name2 = new javax.swing.JLabel();
        marka1 = new javax.swing.JComboBox<>();
        name3 = new javax.swing.JLabel();
        color1 = new javax.swing.JTextField();
        name4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        price1 = new javax.swing.JTextField();
        name5 = new javax.swing.JLabel();
        hara1 = new javax.swing.JTextField();
        name7 = new javax.swing.JLabel();
        check1 = new javax.swing.JCheckBox();
        search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Налични коли");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 220, 40));

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 634, -1, -1));

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 634, -1, -1));

        Gback.setText("Back");
        Gback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GbackActionPerformed(evt);
            }
        });
        getContentPane().add(Gback, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 634, -1, -1));

        reg_number1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_number1ActionPerformed(evt);
            }
        });
        getContentPane().add(reg_number1, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 112, 166, 35));

        fn_students.setText("Рег.номер");
        getContentPane().add(fn_students, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 122, -1, -1));
        getContentPane().add(year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 305, 166, 36));

        namea.setText("Номер на Рама");
        getContentPane().add(namea, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 185, 110, -1));

        Insert.setText("Insert");
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });
        getContentPane().add(Insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 634, -1, -1));
        getContentPane().add(numberRam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 174, 166, 37));

        name2.setText("Марка");
        getContentPane().add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 249, 84, -1));

        marka1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marka1ActionPerformed(evt);
            }
        });
        getContentPane().add(marka1, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 239, 166, 34));

        name3.setText("Година");
        getContentPane().add(name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 316, 58, -1));
        getContentPane().add(color1, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 436, 166, 36));

        name4.setText("Цена");
        getContentPane().add(name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 382, 58, -1));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "reg_number", "numberRam", "marka_name", "year", "price", "color", "harakteristics", "available"
            }
        ));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 112, 774, 425));
        getContentPane().add(price1, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 371, 166, 36));

        name5.setText("Цвят");
        getContentPane().add(name5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 447, 58, -1));
        getContentPane().add(hara1, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 501, 166, 36));

        name7.setText("Характеристики");
        getContentPane().add(name7, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 501, -1, 36));

        check1.setText("Налична ли е колата?");
        getContentPane().add(check1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 565, 208, -1));

        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 59, 166, 35));

        jLabel2.setText("Търсене");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 69, 56, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("E:\\SchoolUpr2_Project_System_imags\\thumb-1920-311249.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
          int row=table1.getSelectedRow();
          String cell=table1.getModel().getValueAt(row, 0).toString();
        Databasea dao=new Databasea();
        String sql="Delete from `carssystem`.`availablecars` where reg_number='" +cell + "'";
        dao.Delete(sql);
        DefaultTableModel model = (DefaultTableModel) table1.getModel();
        model.setRowCount(0);
        dao.SelectTableAvailable(table1,sql1);
    }//GEN-LAST:event_deleteActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        
        Databasea dao=new Databasea();
         if(reg_number1.getText()==null || reg_number1.getText().isEmpty() || numberRam1.getText()==null || numberRam1.getText().isEmpty() ||year1.getText()==null || year1.getText().isEmpty() ||price1.getText()==null || price1.getText().isEmpty() ||color1.getText()==null || color1.getText().isEmpty()||hara1.getText()==null || hara1.getText().isEmpty()){
             JOptionPane.showMessageDialog(null, "Empty fields are not allowed!");
         }else{
        String reg_number=reg_number1.getText();
        if(reg_number.length()>=0 && reg_number.length()<=10){
        String ramNumber=numberRam1.getText();
         int year=Integer.parseInt(year1.getText());
        Double price=Double.parseDouble(price1.getText());
         if(dao.textFieldChange(price)==true)
        {
        String color=color1.getText();
        String selected =marka1.getSelectedItem().toString();
        String sql5="select id_marka from carssystem.marka where name='"+selected+"'";
        dao.SelectedItem(sql5);
        String id=dao.SelectedItem(sql5);
        int id1=Integer.parseInt(id);
        String hara=hara1.getText();
        int available;
        if(check1.isSelected()==true){
            available=1;
        }else{
            available=0;
        }
         int row=table1.getSelectedRow();
         String cell=table1.getModel().getValueAt(row, 0).toString();
        String sql="Update carssystem.availablecars set reg_number='" + reg_number + "',numberRam='" + ramNumber + "',`id_marka`='" + id1 +  "',year='" + year + "',price='" + price + "',color='" + color + "',haracterisitcs='" + hara + "',available='" + available + "'where reg_number='" + cell + "'";
        dao.Update(sql);
        DefaultTableModel model = (DefaultTableModel) table1.getModel();
        model.setRowCount(0);
        dao.SelectTableAvailable(table1,sql1);
         
        }
        }else{
            JOptionPane.showMessageDialog(null, "Registration number length cannot be under zero and bigger than 10!");
        }
         }
    }//GEN-LAST:event_UpdateActionPerformed

    private void GbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GbackActionPerformed
        // TODO add your handling code here:
         MainForm open=new MainForm();
        open.show();
        this.hide();
    }//GEN-LAST:event_GbackActionPerformed

    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertActionPerformed
        // TODO add your handling code here:
               Databasea dao=new Databasea();
               if(reg_number1.getText()==null || reg_number1.getText().isEmpty() || numberRam1.getText()==null || numberRam1.getText().isEmpty() ||year1.getText()==null || year1.getText().isEmpty() ||price1.getText()==null || price1.getText().isEmpty() ||color1.getText()==null || color1.getText().isEmpty()||hara1.getText()==null || hara1.getText().isEmpty()){
             JOptionPane.showMessageDialog(null, "Empty fields are not allowed!");
         }else{
        String reg_number=reg_number1.getText();
          if(reg_number.length()>=0 && reg_number.length()<=10){
        String ramNumber=numberRam1.getText();
        int year=Integer.parseInt(year1.getText());
        Double price=Double.parseDouble(price1.getText());
        if(dao.textFieldChange(price)==true)
        {
        String color=color1.getText();
        String selected =marka1.getSelectedItem().toString();
        String sql5="select id_marka from carssystem.marka where name='"+selected+"'";
        dao.SelectedItem(sql5);
        String id=dao.SelectedItem(sql5);
        int id1=Integer.parseInt(id);
        String hara=hara1.getText();
        int available;
        if(check1.isSelected()==true){
            available=1;
        }else{
            available=0;
        }
        
        String sql="INSERT INTO carssystem.availablecars" + "(reg_number,numberRam,`id_marka`,year,price,color,haracterisitcs,available)"+ "VALUES('" +reg_number + "','" + ramNumber+ "','" + id1+ "','" + year+ "','" + price+ "','" + color+ "','" + hara+ "','" + available+ "')";
        dao.Insert(sql);
        DefaultTableModel model = (DefaultTableModel) table1.getModel();
        model.setRowCount(0);
        dao.SelectTableAvailable(table1,sql1);
        }
        }
        else{
            JOptionPane.showMessageDialog(null, "Registration number length cannot be under zero and bigger than 10!");
        }
               }
        

    }//GEN-LAST:event_InsertActionPerformed

    private void reg_number1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_number1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reg_number1ActionPerformed

    private void marka1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marka1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marka1ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        DefaultTableModel model = (DefaultTableModel) table1.getModel();
        TableRowSorter<TableModel> rowSorter =new TableRowSorter<>(model);
        table1.setRowSorter(rowSorter);
        rowSorter.setRowFilter(RowFilter.regexFilter(search.getText().trim()));
    }//GEN-LAST:event_searchActionPerformed

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        // TODO add your handling code here:
               DefaultTableModel model = (DefaultTableModel) table1.getModel();
String textField = (String) model.getValueAt(table1.getSelectedRow(),0);  
String textField1 = (String) model.getValueAt(table1.getSelectedRow(),1);
String textField6 = (String) model.getValueAt(table1.getSelectedRow(),2);
String textField2 = (String) model.getValueAt(table1.getSelectedRow(),3); 
String textField3 = (String) model.getValueAt(table1.getSelectedRow(),4);  
String textField4 = (String) model.getValueAt(table1.getSelectedRow(),5);
String textField5 = (String) model.getValueAt(table1.getSelectedRow(),6); 
String textField7 = (String) model.getValueAt(table1.getSelectedRow(),7); 
int available;
reg_number1.setText(textField);
numberRam1.setText(textField1);
year1.setText(textField2);
price1.setText(textField3);
color1.setText(textField4);
hara1.setText(textField5);
marka1.setSelectedItem(textField6);
if(textField7.equals("Yes")){
    check1.setSelected(true);
}else{
    check1.setSelected(false);
}

    }//GEN-LAST:event_table1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AvailableCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AvailableCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AvailableCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AvailableCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AvailableCars().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Gback;
    private javax.swing.JButton Insert;
    private javax.swing.JButton Update;
    private javax.swing.JCheckBox check1;
    private javax.swing.JTextField color1;
    private javax.swing.JButton delete;
    private javax.swing.JLabel fn_students;
    private javax.swing.JTextField hara1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> marka1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    private javax.swing.JLabel name5;
    private javax.swing.JLabel name7;
    private javax.swing.JLabel namea;
    private javax.swing.JTextField numberRam1;
    private javax.swing.JTextField price1;
    private javax.swing.JTextField reg_number1;
    private javax.swing.JTextField search;
    private javax.swing.JTable table1;
    private javax.swing.JTextField year1;
    // End of variables declaration//GEN-END:variables
}
