/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.carssystem;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author user
 */
public class sellCars extends javax.swing.JFrame {
String name;
String address;
String phone;
ArrayList<sellCars> list=new ArrayList<sellCars>();

    private sellCars(String name1, String phone1, String address1) {
        this.name=name1;
        this.address=address1;
        this.phone=phone1;
    }
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * Creates new form Teachers
     */
     String sql1="select * from carssystem.sellcars";
     DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
     Date date1 = new Date();
    public sellCars(){
    try {
        initComponents();
        Databasea dao = new Databasea();
        dao.SelectTableCars(table1,sql1);
        dao.combo1(egn);
        dao.combo3(reg);
        String f=dateFormat.format(date1);
        Date date2=new SimpleDateFormat("yyyy-MM-dd").parse(f);
        date.setDate(date2);
    } catch (ParseException ex) {
        Logger.getLogger(sellCars.class.getName()).log(Level.SEVERE, null, ex);
    }
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        namea = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        Insert = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        name2 = new javax.swing.JLabel();
        Update = new javax.swing.JButton();
        reg = new javax.swing.JComboBox<>();
        Gback = new javax.swing.JButton();
        name3 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        egn = new javax.swing.JComboBox<>();
        search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Направени продажби");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 380, -1));

        namea.setText("Дата на продажба");
        getContentPane().add(namea, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 121, -1));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_sell", "dateofSell", "egn", "reg_number"
            }
        ));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 490, 360));

        Insert.setText("Insert");
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });
        getContentPane().add(Insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, -1));

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 570, -1, -1));

        name2.setText("Изберете Егн");
        getContentPane().add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 79, -1));

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, -1, -1));
        getContentPane().add(reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 166, 34));

        Gback.setText("Back");
        Gback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GbackActionPerformed(evt);
            }
        });
        getContentPane().add(Gback, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, -1, -1));

        name3.setText("Изберете Рег.№:");
        getContentPane().add(name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 120, 34));

        date.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 187, 40));
        getContentPane().add(egn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 166, 34));

        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 166, 35));

        jLabel2.setText("Търсене");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 56, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\SchoolUpr2_Project_System_imags\\thumb-1920-311249.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertActionPerformed
        // TODO add your handling code here:
         Databasea dao=new Databasea();
         SimpleDateFormat sdft = new SimpleDateFormat("yyyy-MM-dd");
         String date1 =sdft.format(date.getDate());
        String egn1 =egn.getSelectedItem().toString();
        String reg1 =reg.getSelectedItem().toString();
         String sql="INSERT INTO carssystem.sellcars" + "(dateOfSell,egn,reg_number)"+ "VALUES('" +date1 + "','" + egn1+ "','" + reg1+ "')";
         String sql2="Update carssystem.availablecars set available=0 where reg_number='" +reg1 + "'";
        dao.Insert(sql);
        dao.Update(sql2);
        DefaultTableModel model = (DefaultTableModel) table1.getModel();
        model.setRowCount(0);
        dao.SelectTableCars(table1,sql1);
    }//GEN-LAST:event_InsertActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
          int row=table1.getSelectedRow();
          String cell=table1.getModel().getValueAt(row, 0).toString();
        Databasea dao=new Databasea();
        String sql="Delete from carssystem.sellcars where id_sellCars="+cell;
        dao.Delete(sql);
        DefaultTableModel model = (DefaultTableModel) table1.getModel();
        model.setRowCount(0);
        dao.SelectTableCars(table1,sql1);
    }//GEN-LAST:event_deleteActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
       
        Databasea dao=new Databasea();
         SimpleDateFormat sdft = new SimpleDateFormat("yyyy-MM-dd");
         String date1 =sdft.format(date.getDate());
        String egn1 =egn.getSelectedItem().toString();
        String reg1 =reg.getSelectedItem().toString();
        int row=table1.getSelectedRow();
         String cell=table1.getModel().getValueAt(row, 0).toString();
         
        String sql="Update carssystem.sellcars set dateOfSell ='" + date1 + "',`egn`='" + egn1 + "',`reg_number`='" + reg1 +  "'where id_sellCars="+cell;
        dao.Update(sql);
        DefaultTableModel model = (DefaultTableModel) table1.getModel();
        model.setRowCount(0);
        dao.SelectTableCars(table1,sql1);
    }//GEN-LAST:event_UpdateActionPerformed

    private void GbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GbackActionPerformed
        // TODO add your handling code here:
        MainForm open=new MainForm();
        open.show();
        this.hide();
    }//GEN-LAST:event_GbackActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        DefaultTableModel model = (DefaultTableModel) table1.getModel();
        TableRowSorter<TableModel> rowSorter =new TableRowSorter<>(model);
        table1.setRowSorter(rowSorter);
        rowSorter.setRowFilter(RowFilter.regexFilter(search.getText().trim()));
    }//GEN-LAST:event_searchActionPerformed

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
    try {
        DefaultTableModel model = (DefaultTableModel) table1.getModel();
        String textField = (String) model.getValueAt(table1.getSelectedRow(),1);
        String textField1 = (String) model.getValueAt(table1.getSelectedRow(),2);
        String textField6 = (String) model.getValueAt(table1.getSelectedRow(),3);
        egn.setSelectedItem(textField1);
        reg.setSelectedItem(textField6);
        Date date2=new SimpleDateFormat("yyyy-MM-dd").parse(textField);
        date.setDate(date2);
    } catch (ParseException ex) {
        Logger.getLogger(sellCars.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_table1MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sellCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sellCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sellCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sellCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sellCars().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Gback;
    private javax.swing.JButton Insert;
    private javax.swing.JButton Update;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JButton delete;
    private javax.swing.JComboBox<String> egn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel namea;
    private javax.swing.JComboBox<String> reg;
    private javax.swing.JTextField search;
    private javax.swing.JTable table1;
    // End of variables declaration//GEN-END:variables
}
